
# tasks file for docker_primary

---
- name: Install Docker CE
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repo
  yum_repository:
    name: docker
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Initialize Docker Swarm on primary
  shell: docker swarm init --advertise-addr {{ ansible_host }}
  args:
    creates: /var/lib/docker/swarm

