---
- name: Install and configure NRPE on all servers
  hosts: all
  become: yes
  vars:
    nagios_server_ip: 192.168.1.94   

  tasks:
    - name: Install NRPE and Nagios plugins
      dnf:
        name:
          - nrpe
          - nagios-plugins-all
        state: present

    - name: Ensure NRPE service is enabled and started
      systemd:
        name: nrpe
        enabled: yes
        state: started

    - name: Allow Nagios server IP in NRPE config
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: "allowed_hosts=127.0.0.1,{{ 192.168.1.94 }}"

    - name: Restart NRPE after configuration change
      systemd:
        name: nrpe
        state: restarted

